# Topic: Multicollinearity & Variance Inflation Factor (VIF)

## Definition (30-second explanation)
* Multicollinearity occurs when two or more independent variables (features) in a regression model are highly correlated with each other.
* This prevents the model from isolating the individual effect of each correlated variable, making the coefficients unstable and unreliable.

## Why Interviewers Ask This
* To test your foundational understanding of linear regression assumptions and diagnostics.
* To verify if you know how to handle feature selection, model interpretability, and unstable models in a real-world business context.

## Core Concepts
* **Variance Inflation Factor (VIF):** Quantifies how much the variance of a coefficient is inflated due to multicollinearity.
* **Thresholds:** VIF = 1 means perfect (no multicollinearity). VIF > 5 is moderate (investigate). VIF > 10 indicates severe multicollinearity (take action).
* **Symptoms:** Inflated standard errors, misleading/unreliable p-values (e.g., high R-squared but all p-values > 0.05), and unexpected coefficient signs.

## When to Use (Detection)
* Before fitting any regression model with multiple features.
* When you observe large coefficient changes upon adding or removing features.
* During feature engineering, especially when creating derived features from existing ones.

## Handling Multicollinearity
* **Drop Features:** Remove one of the highly collinear features based on business importance.
* **Regularization:** Use Ridge Regression (L2 penalty) because it inherently handles multicollinearity by shrinking correlated coefficients together.
* **Dimensionality Reduction / Feature Engineering:** Use PCA to combine correlated features into uncorrelated principal components, or create a composite feature (e.g., size/rooms).

## Limitations
* **Prediction vs. Interpretation:** Multicollinearity does NOT hurt prediction accuracy; it only hurts coefficient interpretation.
* **Model Immunity:** Tree-based models (like Random Forest and XGBoost) do not use linear assumptions and are not affected by multicollinearity in the same way.

## Common Comparisons
* **OLS vs. Ridge:** Ordinary Least Squares (OLS) struggles with multicollinearity, whereas Ridge Regression is robust to it due to the L2 penalty.

## Common Interview Traps
* **The Pairwise Trap:** Checking only pairwise correlations; multicollinearity can exist among 3+ features even if pairwise correlation ($r$) is low.
* **The Blind Drop:** Dropping features based solely on VIF > 10 without considering their business importance or predictive power.
* **The Prediction Myth:** Believing that multicollinearity degrades the model's overall predictive performance.

## Python / SQL Syntax
    import pandas as pd
    from statsmodels.stats.outliers_influence import variance_inflation_factor

    # Assuming X is a DataFrame of numerical features
    vif_data = pd.DataFrame()
    vif_data["Feature"] = X.columns
    vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

## Important Formula
$$VIF_i = \frac{1}{1 - R_i^2}$$
*(Where $R_i^2$ is the R-squared value obtained when regressing feature $X_i$ against all other independent features)*

## 45-Second Interview Answer
"Multicollinearity happens when features in a regression model are highly correlated, causing standard errors to inflate and making the coefficients highly unstable. While it doesn’t hurt the model's overall prediction accuracy, it ruins our ability to interpret feature importance. I detect it using the Variance Inflation Factor (VIF); a VIF over 10 indicates a severe issue. To resolve it, I typically drop the least important collinear feature, combine them using PCA, or switch to an L2 regularized model like Ridge regression which handles collinearity naturally."

## Example Questions:

### Practice Question 1
**Q: What is VIF? How do you compute it? What threshold indicates a problem?**

**Ideal Interview Answer:**
VIF, or Variance Inflation Factor, measures how much the variance of an estimated regression coefficient is inflated due to multicollinearity. It is computed by isolating one feature ($X_i$) and running a regression against all other features to get an $R^2$ value. The formula is $VIF_i = \frac{1}{1 - R_i^2}$. A VIF of 1 indicates no multicollinearity, values between 1-5 are moderate, and a VIF > 10 indicates severe multicollinearity that requires intervention.

**Common Mistakes Candidates Make:**
Confusing the $R_i^2$ in the VIF formula with the overall model's R-squared.

**One Likely Interviewer Follow-up:**
"If two features both have a VIF of 15, should you drop both of them simultaneously?" (Answer: No, you should drop only one and recalculate, because removing one often breaks the collinearity and drastically lowers the VIF of the other.)

### Practice Question 2
**Q: Can multicollinearity exist even if no two features have a correlation above 0.5?**

**Ideal Interview Answer:**
Yes. A common mistake is relying solely on pairwise correlation matrices. Multicollinearity can exist among three or more features (multi-collinearity) even if no single pair is highly correlated. For example, feature A might be perfectly predicted by a linear combination of features B, C, and D. This is exactly why we use VIF, as it regresses a feature against *all* other features simultaneously.

**Common Mistakes Candidates Make:**
Answering "No" and stating that a correlation matrix is sufficient to catch all multicollinearity issues.

**One Likely Interviewer Follow-up:**
"How does PCA help in this specific scenario where 3+ variables are tangled together?"(Answer: PCA mathematically transforms the tangled, correlated original features into a new, smaller set of completely uncorrelated variables (principal components) that retain most of the original variance.)

### Practice Question 3
**Q: How does Ridge regression help with multicollinearity compared to OLS?**

**Ideal Interview Answer:**
In OLS, multicollinearity causes the matrix $(X^TX)$ to be nearly singular, leading to wildly unstable and inflated coefficients. Ridge regression solves this by adding an L2 penalty (the sum of squared coefficients multiplied by lambda) to the cost function. This penalty inherently shrinks the coefficients of correlated features towards each other and away from infinity, stabilizing the model and allowing it to handle multicollinearity robustly without dropping features.

**Common Mistakes Candidates Make:**
Confusing Ridge (L2) with Lasso (L1) and saying Ridge performs feature selection by dropping the correlated feature. (Lasso tends to pick one and zero out the other; Ridge shrinks them together).

**One Likely Interviewer Follow-up:**
"Does using Ridge regression fix the interpretability problem caused by multicollinearity?"(Answer: No, while Ridge stabilizes the model's predictions by shrinking coefficients, those shrunk coefficients still represent blended effects and cannot be cleanly interpreted as independent feature impacts.)

### Practice Question 4
**Q: In a model with 20 features, how would you systematically identify and handle multicollinearity?**

**Ideal Interview Answer:**
First, I would generate a correlation matrix as a quick check for obvious pairwise collinearity. Next, I would compute the VIF for all 20 features. If any features have a VIF > 10, I wouldn't drop them all at once. I would drop the single feature with the highest VIF (while also considering its business value), and then recompute the VIFs for the remaining 19 features, because dropping one feature often drastically lowers the VIF of the others. I'd repeat this iteratively until all VIFs are under acceptable thresholds.

**Common Mistakes Candidates Make:**
Suggesting dropping *all* features with VIF > 10 at the exact same time, which deletes useful data since removing just one often fixes the inflation for the rest.

**One Likely Interviewer Follow-up:**
"Write a Python function to automate this iterative dropping process."

## Practice Questions:

### Q1: Iterative VIF Reduction

**Q: Write a Python function to iteratively remove features with a VIF above a certain threshold.**
Based on our discussion about not dropping all high-VIF features at once, can you write a Python function named calculate_and_drop_vif(X, threshold=10.0)? This function should take a pandas DataFrame X and iteratively drop the feature with the highest VIF until all remaining features have a VIF below the threshold. Return the filtered DataFrame.

In [19]:
# Data:
import pandas as pd
import numpy as np

# Mock DataFrame 'df' with 4 features (Size, Rooms, Age, Bathrooms)
# Size and Rooms are highly correlated.
np.random.seed(42)
size = np.random.normal(1500, 300, 100)
rooms = size / 250 + np.random.normal(0, 0.5, 100)
age = np.random.normal(10, 5, 100)
bathrooms = size / 750 + np.random.normal(0, 0.2, 100)

X = pd.DataFrame({'Size': size, 'Rooms': rooms, 'Age': age, 'Bathrooms': bathrooms})

In [21]:
X

           Size     Rooms        Age  Bathrooms
0   1649.014246  5.888372  11.788937   2.032887
1   1458.520710  5.623760  12.803923   1.832658
2   1694.306561  6.605869  15.415256   2.408534
3   1956.908957  7.426497  15.269010   2.731286
4   1429.753988  5.638373   3.111653   1.902158
..          ...       ...        ...        ...
95  1060.945516  4.436441   6.535452   1.320759
96  1588.836083  5.913416  14.497999   1.775821
97  1578.316582  6.390129  11.536498   2.375197
98  1501.534037  6.035241  14.064311   1.979137
99  1429.623860  5.147010  13.148144   2.153728

[100 rows x 4 columns]

In [20]:
import pandas as pd
from statsmodels.stats.outliers_influence import variance_inflation_factor

def calculate_and_drop_vif(X, threshold=10.0):
    """
    Iteratively drops the feature with the highest VIF until all are below the threshold.
    """
    X_clean = X.copy()
    
    while True:
        # Calculate VIF for all current features
        vif = pd.Series(
            [variance_inflation_factor(X_clean.values, i) for i in range(X_clean.shape[1])],
            index=X_clean.columns
        )
        
        max_vif = vif.max()
        
        # Stop if the highest VIF is within acceptable limits
        if max_vif < threshold:
            break
            
        # Identify and drop the worst offending feature
        feature_to_drop = vif.idxmax()
        X_clean = X_clean.drop(feature_to_drop, axis=1)
        
    return X_clean

In [22]:
X_filtered= calculate_and_drop_vif(X= X, threshold= 10.0)
X_filtered

       Rooms        Age
0   5.888372  11.788937
1   5.623760  12.803923
2   6.605869  15.415256
3   7.426497  15.269010
4   5.638373   3.111653
..       ...        ...
95  4.436441   6.535452
96  5.913416  14.497999
97  6.390129  11.536498
98  6.035241  14.064311
99  5.147010  13.148144

[100 rows x 2 columns]

**Interview Tips:**
- Use .values: The variance_inflation_factor function expects a numpy array, not a pandas DataFrame. Always pass X.values.
- Use .idxmax(): This is the cleanest way to find the column name associated with the highest VIF score without writing complex loops.
- Copy the DataFrame: Start with X_clean = X.copy() to avoid mutating the original dataset passed by the interviewer.